name: Publish Beta Package

on:
  push:
    branches:
      - develop

jobs:
  publish-beta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"

      - name: Install dependencies
        run: npm install

      - name: Build the package
        run: npm run build

      - name: Publish to npm (beta)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --tag beta

      - name: Publish to pnpm (beta)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx pnpm publish --tag beta

      - name: Publish to Yarn (beta)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn publish --tag beta
