name: Publish to npm registry

on:
  release:
    types: [released]

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npx pnpm install

      - name: Build packages
        run: npx pnpm run build:packages

      - name: Get changed packages
        id: changed-packages
        run: echo "changed_packages=$(npx pnpm run build:packages --dry-run=json | jq -r '.tasks[].package')" >> $GITHUB_ENV

      - name: Publish all packages
        if: env.changed_packages != ''
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          for package in $changed_packages; do
            echo "Publishing $package"
            npx pnpm --filter $package publish --provenance --access public --no-git-checks || exit 1
          done
